services:
  - type: web
    name: devops-portfolio-api
    env: node
    plan: free
    region: oregon

    buildCommand: "npm install"
    startCommand: "node server/index.js"

    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: FROM_EMAIL
        sync: false
      - key: TO_EMAIL
        sync: false

    autoDeploy: true

    disk:
      name: inbox
      mountPath: /opt/render/project/src/server/_inbox
      sizeGB: 1